### ISSUE TITLE
[To do/Doing] Add vless support

### ISSUE THREAD

**Issue by ariadarkkkis** [lotusproxy/lotusboard#1]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

Please add vless support + reality. Thanks

**Comment by ariadarkkkis** [comment]
Thanks for the effort. Xray-core is planning to remove XTLS so there is no point in having it. Of course, we still need to configure flow (Vision for now but maybe more in the future) because of reality.
I saw XrayR documentation about reality and currently seems impossible to do a lot of configuration remotely but I assume it's still in test and Im sure all of those configurations can be set remotely and XrayR will read them from the panel. But after all, it's the panel that generates the configuration for the client and that's why I said it.
My idea is maybe to add another option under TLS called Reality and have its own custom configuration for these and then read those values and parse them into Vless URI but with reality parameters. There was a document about reality URI configuration I just can't find it (for v2ray-based configs), but here is the Clash Meta documentation if you need it: [Clash.Meta config documentation](https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml)

**Comment by ariadarkkkis** [comment]
> 

I think its confusing to have to set `cipher` to `zero` in order to tell the system its vless. You can add another type just like vmess, trojan and shadowsocks and then do your work based on that type. Its cleaner and more understandable.

**Comment by lotusproxy** [comment]
We are going to add vless support
