### ISSUE TITLE
Backup methode

### ISSUE THREAD

**Issue by lahirubro123** [lotusproxy/lotusboard#14]
Can you Add panel data Backup and Restore Option ?

**Comment by lotusproxy** [comment]
Sure

**Comment by lotusproxy** [comment]
https://github.com/lotusproxy/lotusboard-docker/wiki/How-to-backup-lotusboard

Done.

**Comment by lahirubro123** [comment]
If i backup as this so then how can i restore it to a nother vps

**Comment by lotusproxy** [comment]
tar xf lotusboard-backup.tar.gz
cd lotusboard-docker
docker compose up -d
