### ISSUE TITLE
can not connect lotusboard docker mysql 

### ISSUE THREAD

**Issue by okoklai** [lotusproxy/lotusboard#16]
I have setup the docker-composer.ymal like this
_____________________________________________________________

version: '3'
services:
  www:
    image: ghcr.io/lotusproxy/sakuraneko
    volumes:
      - './lotusboard:/www'
      - './wwwlogs:/wwwlogs'
      - './caddy.conf:/run/caddy/caddy.conf'
      - './supervisord.conf:/run/supervisor/supervisord.conf'
      - './crontabs.conf:/etc/crontabs/root'
      - './.caddy:/root/.caddy'
    links:
      - mysql
    ports:
      - '80:80'

    restart: always
  mysql:
    image: mysql:5.7.29
    volumes:
      - './mysql:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '@@@@AABB12031203'
      MYSQL_DATABASE: 1stv2board

____________________________________________________________________
then I run init.sh it tips cannot connect the datebase.
____________________________________________________________________

`
请输入数据库地址（默认:localhost） [localhost]:
 > localhost

 请输入数据库名:
 > 1stv2board

 请输入数据库用户名:
 > root

 请输入数据库密码:
 > @@@@AABB12031203

数据库连接失败
`

**Comment by lotusproxy** [comment]
It looks like the database is unavailable on your instance

Please check your database and try to find out the cause

It's possible that mysql is not ready, please read logs first by using `docker compose logs -ft`, after mysql is ready for new connection, enter the www container and rm .env, then re-run the setup script

**Comment by lotusproxy** [comment]
Also try to remove @@@@ in your mysql password

**Comment by okoklai** [comment]
Found the cause of the error,It not enough memory of my VPS(1C1G).

**Comment by lotusproxy** [comment]
> Found the cause of the error,It not enough memory of my VPS(1C1G). 

Good, you can fix it by adding swap manually...
