### ISSUE TITLE
[DOCS] 使用默认的 default.clash.yaml,会导致报错

### ISSUE THREAD

**Issue by shizeying** [lotusproxy/lotusboard#21]
报错如下: 托管配置文件格式不正确: yaml: unmarshal errors:
line 24: cannot unmarshal !!map into []string; 
或者:托管配置文件格式不正确: proxy group[0]: Switcher: 'Auto' not found
- 能否发出一些实例的 custom.*的文件,提供一个参考
- 使用 neo分支,稳定版

**Comment by shizeying** [comment]
另外能否请教一下:关于支持QuantumultX的功能以及对应配置方式的实例

**Comment by lotusproxy** [comment]
> 报错如下: 托管配置文件格式不正确: yaml: unmarshal errors:
> line 24: cannot unmarshal !!map into []string; 
> 或者:托管配置文件格式不正确: proxy group[0]: Switcher: 'Auto' not found
> - 能否发出一些实例的 custom.*的文件,提供一个参考
> - 使用 neo分支,稳定版

你使用的节点类型？配置？

**Comment by shizeying** [comment]
我使用了 vless 节点;也使用了 vmess 和 trojan 都会导致该问题.我使用了 clash x pro ,系统是 macos

**Comment by lotusproxy** [comment]
> 我使用了 vless 节点;也使用了 vmess 和 trojan 都会导致该问题.我使用了 clash x pro ,系统是 macos

麻烦请你curl clash订阅下来看看它出错的那行写了什么 这样就能更精确的定位到问题的根源

**Comment by shizeying** [comment]
不是,我使用 default 默认的就会有问题

**Comment by lotusproxy** [comment]
> 不是,我使用 default 默认的就会有问题
> 


我知道 听说clashX不能redir 我们默认用的就是redir 所以麻烦你检查一下是不是因为这个原因导致错误

如果是的话那需要你自己在你的那边搞一个custom.clash.yaml了，这样他就会读这个而不是default

**Comment by shizeying** [comment]
vless+reality 这个该什么时候进行提供呢?麻烦问下

**Comment by lotusproxy** [comment]
> vless+reality 这个该什么时候进行提供呢?麻烦问下

V2board official is going to add VLESS so probably after 1.7.5 released,
What we provide is an enhanced v2board, it's still v2board but enhanced

So we try to keep it "vanilla"
