### ISSUE TITLE
:sparkles: 增加QuantumultX;ClashMeta;Stash等常用规则

### ISSUE THREAD

**Issue by shizeying** [lotusproxy/lotusboard#22]
1. 我看源码中没有这几个的对应实现,也就是说没有这几个功能;能否支持这几个客户端的;谢谢;
2. 另外再官网,我看有对应的实现了

**Comment by lotusproxy** [comment]
1 默认支持clash meta 不支持 clash
2 下个版本会加回来 等v2board发1.7.5

**Comment by shizeying** [comment]
- 谢谢,我已经阅读了您的代码,我发现在 trojan 搭配 XTLS 的时候,并没有加入 xtls-rprc-direct的支持,能否加入这个优化呢

**Comment by lotusproxy** [comment]
> - 谢谢,我已经阅读了您的代码,我发现在
> 1.  trojan 搭配 XTLS 的时候,并没有加入 xtls-rprc-direct的支持,能否加入这个优化呢
> 2. quanx 等配置中并没有加入对 vless 的支持

就是 你有没有考虑一个问题 qx根本就不支持vless和hy

而且现在是2023了 谁还用direct啊 一用秒没

**Comment by shizeying** [comment]
好的谢谢!
