### ISSUE TITLE
[To do/Doing]Support Naive 

### ISSUE THREAD

**Issue by Kingroyal78** [lotusproxy/lotusboard#5]
Hello,Will you support Naive on the panel?

**Comment by lotusproxy** [comment]
In theory this can be done(by using some "hacking" method since we don't have the source code for frontend),but there's no standard for NaiveProxy at all(for now)

**Comment by Kingroyal78** [comment]
It's fine.I am very excited about the progress of the project

**Comment by lotusproxy** [comment]
After Vless goes to the neo-latest-stable branch we can start working on naiveproxy

**Comment by lotusproxy** [comment]
~~wait for a month~~

**Comment by lotusproxy** [comment]
Sorry, won't do
